name = "nodematiclabs"
main = "hostel-management-backend/main.go"
workers_dev = false

[main.modules]
  [main.modules."hostel-management-backend"]
    path = "hostel-management-backend"
    bucket = "hostel-management-backend"
    command = "go run main.go"
    env = {
      PORT = "8080"
    }
bucket = "hostel-management-backend"
